<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <OutputType>WinExe</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.3.14" />
        <PackageReference Include="Avalonia.Desktop" Version="11.3.14" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.14" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.14" />
        <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.1">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
        <PackageReference Include="IconPacks.Avalonia" Version="2.0.0" />
        <PackageReference Include="NAudio" Version="2.3.0" />
        <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="11.0.0-preview.4.26230.115" />
    </ItemGroup>

    <ItemGroup>
      <AvaloniaResource Include="Assets\**" />
    </ItemGroup>
</Project>
